use_frameworks!

target 'upyun-sdk_Example' do
  pod 'upyun-sdk', :path => '../'
  pod 'SnapKit', '~> 3.2.0'

  target 'upyun-sdk_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
